name: frontend
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  image_picker: ^1.1.2
  http: ^1.2.2
  mime: ^1.0.4 
  google_fonts: ^6.0.0
  flutter_animate: ^4.5.0
  shared_preferences: ^2.1.0
  cupertino_icons: ^1.0.8
  flutter_keyboard_visibility: ^6.0.0
  http_parser: ^4.1.2
  mapbox_maps_flutter: ^2.2.0
  permission_handler: ^11.0.1
  geolocator: ^14.0.2
  flutter_dotenv: ^6.0.0
  flutter_map: ^8.2.2
  latlong2: ^0.9.1
  cached_network_image: ^3.3.0
  flutter_cache_manager: ^3.3.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/suchance.png
    - assets/icons/
    - .env